# Use a lightweight, Alpine-based image of the latest OpenJDK 17
FROM eclipse-temurin:17-jre-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the Spring Boot app JAR file to the container
COPY target/{{projectName}}-1.0-SNAPSHOT.jar {{projectName}}.jar

# Run the Spring Boot app when the container starts
CMD ["java", "-jar", "{{projectName}}.jar"]
